### ISSUE TITLE
Add "contribute" and "replicate" buttons to project page

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#125]
Requirements outline here:
https://docs.google.com/document/d/1AK0EG_psBD6sy1ZLs268NURq4yrqji7vp118KlmLS8k/edit

Design here: 
https://civicmakers.slack.com/files/ollie/F0JDK32MS/story-v1-pitch.png

**Comment by ybentz** [comment]
@grodeska the design link doesn't work.. 
Did you mean this one? 
https://civicmakers.slack.com/files/ollie/F0JDE8QFM/story-v1-pitch.png

**Comment by grodeska** [comment]
That's the one!

On Thu, Jan 21, 2016 at 5:58 PM, ybentz notifications@github.com wrote:

> @grodeska https://github.com/grodeska the design link doesn't work..
> Did you mean this one?
> https://civicmakers.slack.com/files/ollie/F0JDE8QFM/story-v1-pitch.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/125#issuecomment-173775746.

## 

Lawrence Grodeska
Founder & CEO
CivicMakers http://civicmakers.com
415-819-8495
