### ISSUE TITLE
Add "start a project guide" page

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#146]
As a user, I would like to see a guide to starting my own project. I can access this guide from the "do this in my area" button on the project page. 

This page should be a new view.

Url for this page should be: civicmakers.com/start-a-project-guide

Content is forthcoming from Lawrence

**Comment by ybentz** [comment]
@grodeska, I added the new page as requested, you can edit the content under 'projects/startProjectGuide/startProjectGuide.html'.
For now it's just meant to be styled text only, if you want to add functionality to it (buttons or anything of that sort) let me know and I'll add that also.

**Comment by grodeska** [comment]
Great! Thanks, Yonatan. Will get that content up shortly.

On Mon, Feb 1, 2016 at 12:31 PM, ybentz notifications@github.com wrote:

> @grodeska https://github.com/grodeska, I added the new page as
> requested, you can edit the content under
> 'projects/startProjectGuide/startProjectGuide.html'.
> For now it's just meant to be styled text only, if you want to add
> functionality to it (buttons or anything of that sort) let me know and I'll
> add that also.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/146#issuecomment-178173068.

## 

Lawrence Grodeska
Founder & CEO
CivicMakers http://civicmakers.com
415-819-8495
