### ISSUE TITLE
New tab defaults not working

### ISSUE THREAD

**Issue by ondrae** [civicmakers/client#184]
#### Description

When I was adding a new project, I filled out the whole form. The final step is look up a tool on another page. I tried to `command click` the title logo to open a new tab so I could go look at Tools. Instead of a new tab it went to the home page in my current tab and lost all my form data.
#### To reproduce

Try to open any link in a new tab.

**Comment by grodeska** [comment]
Ah, got it. Thanks, @ondrae! Pinging @ybentz. 

Also, Andrew, if you have thoughts about how to make the instructions more clear (at least until we can programmatically address), we're all ears.

**Comment by ybentz** [comment]
@ondrae great feedback! Thank you!

@grodeska I'll push a quick fix now.
