### ISSUE TITLE
Update auth screen Twitter image

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#189]
The image used on the Twitter auth screen is our old logo. It also says "by Code for San Francisco." This should be updated to use our current twitter avatar (twitter.com/civicmakers) and "by CivicMakers."

**Comment by grodeska** [comment]
![img_5406](https://cloud.githubusercontent.com/assets/7856430/13237084/bc6e8732-d97d-11e5-9dc1-1582f78e3082.PNG)

**Comment by ybentz** [comment]
Done. @grodeska can you make sure all the details are correct now?

**Comment by grodeska** [comment]
That worked! All details are correct. Thanks :)

On Mon, Feb 22, 2016 at 4:22 PM, ybentz notifications@github.com wrote:

> Done. @grodeska https://github.com/grodeska can you make sure all the
> details are correct now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/189#issuecomment-187448933.

## 

Lawrence Grodeska
Founder & CEO
CivicMakers http://civicmakers.com
415-819-8495
