### ISSUE TITLE
Only display fields on profilecard if data exists

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#86]
On profileCard directive, fields should only be displayed if data exists (Twitter, URL, tags, etc.)

![screen shot 2015-12-02 at 9 31 27 pm](https://cloud.githubusercontent.com/assets/7856430/11552686/25e332ee-993c-11e5-9af5-6815ab6b6ab8.png)

**Comment by ybentz** [comment]
Fixed by https://github.com/civicmakers/client/commit/623d0da21cbbe713c1228f9af7041f17e9e3f069
@grodeska can you make sure it works and close it?

**Comment by grodeska** [comment]
Looks great!
