### ISSUE TITLE
On homepage cards, longer project name pushes pricing to a 2nd line

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#94]
Longer project name pushes Pricing to a 2nd line – longer project names should truncate or wrap to 2nd line while pricing stays on top line, aligned right

**Comment by ybentz** [comment]
@cpalmatier or @olliebeannn, both of @grodeska's suggestions are pretty easy to do, which should I implement? (truncate with ... or multiline)

**Comment by olliebeannn** [comment]
I'm in favour of truncating to keep things compact (could imagine a few
names getting really long since we don't cap the length).

On 10 December 2015 at 13:58, ybentz notifications@github.com wrote:

> @cpalmatier https://github.com/cpalmatier or @olliebeannn
> https://github.com/olliebeannn, both of @grodeska
> https://github.com/grodeska's suggestions are pretty easy to do, which
> should I implement? (truncate with ... or multiline)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/94#issuecomment-163761403.

## 

olliekhakwani.com http://www.olliekhakwani.com
650.804.4313

**Comment by cpalmatier** [comment]
+1

**Comment by grodeska** [comment]
Design has spoken! Make it so :)

On Friday, December 11, 2015, chris palmatier notifications@github.com
wrote:

> +1
> 
> > On Dec 10, 2015, at 10:30 PM, Ollie Khakwani <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > I'm in favour of truncating to keep things compact (could imagine a few
> > names getting really long since we don't cap the length).
> > 
> > On 10 December 2015 at 13:58, ybentz <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > @cpalmatier https://github.com/cpalmatier or @olliebeannn
> > > https://github.com/olliebeannn, both of @grodeska
> > > https://github.com/grodeska's suggestions are pretty easy to do,
> > > which
> > > should I implement? (truncate with ... or multiline)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/civicmakers/client/issues/94#issuecomment-163761403>.
> > 
> > ## 
> > 
> > olliekhakwani.com http://www.olliekhakwani.com
> > 650.804.4313
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/94#issuecomment-163876759.

## 

@grodeska http://twitter.com/grodeska
http://grodeska.com
415-819-8495

**Comment by grodeska** [comment]
@ybentz In case you missed it, a consensus was reached above on a design decision.

**Comment by ybentz** [comment]
@grodeska thanks.. Just got back to the west coast, I'll probably do it tomorrow

**Comment by grodeska** [comment]
Cool. No rush, @ybentz.

On Monday, December 14, 2015, ybentz notifications@github.com wrote:

> @grodeska https://github.com/grodeska thanks.. Just got back to the
> west coast, I'll probably do it tomorrow
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/94#issuecomment-164601594.

## 

@grodeska http://twitter.com/grodeska
http://grodeska.com
415-819-8495

**Comment by ybentz** [comment]
Hey @olliebeannn @cpalmatier, I got it to work as we discussed but I think that it's not optimal since the card are pretty narrow and if the price is freemium then there's not so much space left for the name (see screenshot below).

<img width="1334" alt="screen shot 2015-12-15 at 2 21 30 pm" src="https://cloud.githubusercontent.com/assets/14811577/11825979/56b6b396-a337-11e5-9c7d-c82c07f6e7b6.png">

Also the only way to do it is using css flexbox which as far as I know is supported by most modern browsers but might cause problems with some browsers.

What I suggest is maybe move the price to be below the name like so:

<img width="1049" alt="screen shot 2015-12-15 at 2 25 27 pm" src="https://cloud.githubusercontent.com/assets/14811577/11826058/c4c43bce-a337-11e5-9bee-c9c68593cc08.png">

Let me know what you think.

**Comment by grodeska** [comment]
I generally like this approach. Curious what @olliebeannn & @cpalmatier
think. Also, did we ever decide how to approach the tags when there are
more than the card height will allow?

On Tue, Dec 15, 2015 at 5:56 PM, ybentz notifications@github.com wrote:

> Hey @olliebeannn https://github.com/olliebeannn @cpalmatier
> https://github.com/cpalmatier, I got it to work as we discussed but I
> think that it's not optimal since the card are pretty narrow and if the
> price is freemium then there's not so much space left for the name (see
> screenshot below).
> 
> [image: screen shot 2015-12-15 at 2 21 30 pm]
> https://cloud.githubusercontent.com/assets/14811577/11825979/56b6b396-a337-11e5-9c7d-c82c07f6e7b6.png
> 
> Also the only way to do it is using css flexbox which as far as I know is
> supported by most modern browsers but might cause problems with some
> browsers.
> 
> What I suggest is maybe move the price to be below the name like so:
> 
> [image: screen shot 2015-12-15 at 2 25 27 pm]
> https://cloud.githubusercontent.com/assets/14811577/11826058/c4c43bce-a337-11e5-9bee-c9c68593cc08.png
> 
> Let me know what you think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/94#issuecomment-164916860.

## 

@grodeska http://twitter.com/grodeska
http://grodeska.com
415-819-8495

**Comment by ybentz** [comment]
I don't think we decided what to do with the tags yet so I'll open a separate bug for it and tag Ollie and Chris

**Comment by olliebeannn** [comment]
I think moving the pricing to the next line makes sense.

I'm heading back to England tonight but I'm planning on going over the
visual design again while I'm there to better adapt it to the content, and
I'll send updates over the Xmas/New Year's break.

**Comment by grodeska** [comment]
Awesome, thanks @olliebeannn! Have a great trip :)

On Thu, Dec 17, 2015 at 1:42 PM, Ollie Khakwani notifications@github.com
wrote:

> I think moving the pricing to the next line makes sense.
> 
> I'm heading back to England tonight but I'm planning on going over the
> visual design again while I'm there to better adapt it to the content, and
> I'll send updates over the Xmas/New Year's break.
> On Thu, Dec 17, 2015 at 10:36 AM, ybentz notifications@github.com wrote:
> 
> > I don't think we decided what to do with the tags yet so I'll open a
> > separate bug for it and tag Ollie and Chris
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/civicmakers/client/issues/94#issuecomment-165541552
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/94#issuecomment-165543823.

## 

@grodeska http://twitter.com/grodeska
http://grodeska.com
415-819-8495

**Comment by ybentz** [comment]
Fixed by https://github.com/civicmakers/client/pull/112
