### ISSUE TITLE
Profile menu in nav bar floats to left

### ISSUE THREAD

**Issue by grodeska** [civicmakers/client#95]
Profile menu in nav bar should instead float to the right edge of content width. 

![screen shot 2015-12-07 at 1 06 10 pm](https://cloud.githubusercontent.com/assets/7856430/11639740/71f02372-9ce3-11e5-9f44-48ce12cf2d76.png)

**Comment by ybentz** [comment]
@grodeska can we close this one? Seems like it's working as wanted.
If not then let me know what's the issue and I'll look into it.

**Comment by grodeska** [comment]
Yeah, we can close this one.

On Thursday, December 17, 2015, ybentz notifications@github.com wrote:

> @grodeska https://github.com/grodeska can we close this one? Seems like
> it's working as wanted.
> If not then let me know what's the issue and I'll look into it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/civicmakers/client/issues/95#issuecomment-165585100.

## 

@grodeska http://twitter.com/grodeska
http://grodeska.com
415-819-8495
